/*The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
What is the first triangle number to have over five hundred divisors?*/

// count the divisor of ingeter
function divisorCount(num) {
  let count = 0;
  for (let i = 1; i < Math.sqrt(num); i++) {
    if (num % i === 0) count += 2;
  }
  if (num % Math.sqrt(num) === 0) count += 1;
  return count;
}

// generate the nth triangular number
function triangular(n) {
  let target = 0;
  for (let i = 1; i <= n; i++) {
    target += i;
  }
  return target;
}

function firstNdivisor(n) {
  let i = 1;
  while (true) {
    let target = triangular(i);
    if (divisorCount(target) > n) {
      return target;
    }
    i++;
  }
}

console.log(firstNdivisor(5));
console.log(firstNdivisor(23));
console.log(firstNdivisor(167));
console.log(firstNdivisor(374));
console.log(firstNdivisor(500));
