# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimized; what is the value of D?

# pj = j(3j - 1)/2 = 1/2 * (3 * j^2 - j)
# pk = k(3k - 1)/2 = 1/2 * (3 * k^2 - k)
# pk + pj = 1/2 () 

def pentagon_num():
    