# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle      Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
 
# Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
 
# Hexagonal     Hn=n(2n−1)      1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
import math
def tri_pen_hex(n):
    i = (1 + math.sqrt(8 * n + 1)) // 4 + 1  # we start after 40755 (H143 = 40755)
    while True:
        h = i * (2 * i - 1)
        # skip checking is_triangular() because all hexagonal numbers are triangular.
        if is_pentagonal(h):
            return h
        i += 1

def is_triangular(n):
    x = (math.sqrt(8 * n + 1) - 1) / 2
    return x.is_integer()

def is_pentagonal(n):
    x = (1 + math.sqrt(24 * n + 1)) / 6
    return x.is_integer()

def is_hexagonal(n):
    x = (1 + math.sqrt(8 * n + 1)) / 4
    return x.is_integer()